name: Build Internal
on:
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        description: 'Build type'
        default: 'release'
        options:
        - release
        - internal
 # schedule:
  #  - cron: '30 * * * *'
     
      
     
    
jobs:
  release:
    if: (inputs.build_type == 'release') || (github.event_name == 'schedule')
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 2
        run: echo This step Release
        
  internal:
    if: inputs.build_type == 'internal'
    runs-on: ubuntu-latest
    
    steps:
      - name: Print the input tag to STDOUT
        run: echo  Internal job 
        
     
